#include <velo/lexer/token_kind.h>

namespace Velo::Lexer {
    auto toString(const TokenKind kind) -> std::string_view {
        switch (kind) {
            case TokenKind::EndOfFile:
                return "EndOfFile";
            case TokenKind::Invalid:
                return "Invalid";
            case TokenKind::Identifier:
                return "Identifier";
            case TokenKind::IntegerLiteral:
                return "IntegerLiteral";
            case TokenKind::StringLiteral:
                return "StringLiteral";
            case TokenKind::KwModule:
                return "KwModule";
            case TokenKind::KwUse:
                return "KwUse";
            case TokenKind::KwAs:
                return "KwAs";
            case TokenKind::KwFn:
                return "KwFn";
            case TokenKind::KwReturn:
                return "KwReturn";
            case TokenKind::KwPub:
                return "KwPub";
            case TokenKind::DoubleColon:
                return "DoubleColon";
            case TokenKind::Colon:
                return "Colon";
            case TokenKind::Semicolon:
                return "Semicolon";
            case TokenKind::Comma:
                return "Comma";
            case TokenKind::OpenParen:
                return "OpenParen";
            case TokenKind::CloseParen:
                return "CloseParen";
            case TokenKind::OpenBrace:
                return "OpenBrace";
            case TokenKind::CloseBrace:
                return "CloseBrace";
            case TokenKind::Plus:
                return "Plus";
            case TokenKind::KwLet:
                return "KwLet";
            case TokenKind::Equal:
                return "Equal";
            case TokenKind::KwVar:
                return "KwVar";
            case TokenKind::BooleanLiteral:
                return "BooleanLiteral";
            case TokenKind::KwIf:
                return "KwIf";
            case TokenKind::KwElse:
                return "KwElse";
            case TokenKind::EqualEqual:
                return "EqualEqual";
            case TokenKind::BangEqual:
                return "BangEqual";
            case TokenKind::Less:
                return "Less";
            case TokenKind::Greater:
                return "Greater";
            case TokenKind::LessEqual:
                return "LessEqual";
            case TokenKind::GreaterEqual:
                return "GreaterEqual";
            case TokenKind::KwWhile:
                return "KwWhile";
            case TokenKind::KwBreak:
                return "KwBreak";
            case TokenKind::KwContinue:
                return "KwContinue";
            case TokenKind::LogicalAnd:
                return "LogicalAnd";
            case TokenKind::LogicalOr:
                return "LogicalOr";
            case TokenKind::Bang:
                return "Bang";
            case TokenKind::Minus:
                return "Minus";
            case TokenKind::Star:
                return "Star";
            case TokenKind::Percent:
                return "Percent";
            case TokenKind::Slash:
                return "Slash";
            case TokenKind::KwStruct:
                return "KwStruct";
            case TokenKind::Dot:
                return "Dot";
            case TokenKind::OpenBracket:
                return "OpenBracket";
            case TokenKind::CloseBracket:
                return "CloseBracket";
            case TokenKind::At:
                return "At";
        }

        return "Unknown";
    }
}
